config/routes.rb
Rails.application.routes.draw do
  #resources :second_pages
  resources :first_pages
  root 'first_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/first_page.rb
class FirstPage < ApplicationRecord
end

app/models/second_page.rb
class SecondPage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/first_pages_controller.rb
class FirstPagesController < ApplicationController
  before_action :set_first_page, only: [:show, :edit, :update, :destroy]

  # GET /first_pages
  # GET /first_pages.json
  def index
    #this is the first page
    @first_pages = FirstPage.all
  end

  # GET /first_pages/1
  # GET /first_pages/1.json
  def show
  end

  # GET /first_pages/new
  # redirect to second page
  def new
   @first_page = FirstPage.new
  end

  # GET /first_pages/1/edit
  def edit
  end

  # POST /first_pages
  # POST /first_pages.json
  def create
    @first_page = FirstPage.new(first_page_params)

    respond_to do |format|
      if @first_page.save
        format.html { redirect_to @first_page, notice: 'First page was successfully created.' }
        format.json { render :show, status: :created, location: @first_page }
      else
        format.html { render :new }
        format.json { render json: @first_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /first_pages/1
  # PATCH/PUT /first_pages/1.json
  def update
    respond_to do |format|
      if @first_page.update(first_page_params)
        format.html { redirect_to @first_page, notice: 'First page was successfully updated.' }
        format.json { render :show, status: :ok, location: @first_page }
      else
        format.html { render :edit }
        format.json { render json: @first_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /first_pages/1
  # DELETE /first_pages/1.json
  def destroy
    @first_page.destroy
    respond_to do |format|
      format.html { redirect_to first_pages_url, notice: 'First page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_first_page
      @first_page = FirstPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def first_page_params
      params.fetch(:first_page, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_pages_helper.rb
module FirstPagesHelper
end

app/helpers/second_pages_helper.rb
module SecondPagesHelper
end

app/views/first_pages/_form.html.erb
<%= form_for(first_page) do |f| %>
  <% if first_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(first_page.errors.count, "error") %> prohibited this first_page from being saved:</h2>

      <ul>
      <% first_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/first_pages/edit.html.erb
<h1>Editing First Page</h1>

<%= render 'form', first_page: @first_page %>

<%= link_to 'Show', @first_page %> |
<%= link_to 'Back', first_pages_path %>

app/views/first_pages/index.html.erb
<p id="notice">
   <%= notice %>
</p>
<div class="my_text_data">    
    <h1>Home Page</h1>    
    <table>
       <thead>
           <tr>
               <th colspan="3"></th>
           </tr>
       </thead>        
       <tbody>
           <% @first_pages.each do |first_page| %>
               <tr>
                   <td>
                       <%= link_to 'Show', first_page %>
                   </td>
                   <td>
                       <%= link_to 'Edit', edit_first_page_path(first_page) %>
                   </td>
                   <td>
                       <%= link_to 'Destroy', first_page, method: :delete, data: { confirm: 'Are you sure?' } %>
                   </td>
               </tr>
               <% end %>
       </tbody>
   </table>  
     <br>    
     <%= link_to 'New First Page', new_first_page_path %>
  </div>
   <div class="modal-mask">
     <div class="modal" tabindex="1">
     <p align="center">
          Session Time Out
           <br>
           <button class="modal-btn">Okay</button>
       </p>
   </div>
 </div>


 

app/views/first_pages/new.html.erb
<h1>Redirect to Second Page!</h1>

<%= render 'form', first_page: @first_page %>

<%= link_to 'Back', first_pages_path %>

app/views/first_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_first_page_path(@first_page) %> |
<%= link_to 'Back', first_pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld</title>
    <%= csrf_meta_tags %>

    <script
    src="http://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>